services:
  redis:
    image: redis:7.2.4
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
      - 6379:6379
    networks:
      - shopping-app
  
  app: 
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - shopping-app
    
networks:
  shopping-app:
    driver: bridge

